### ISSUE TITLE
🔥 [HIGH] Enhance Rate Limiting Implementation

### ISSUE THREAD

**Issue by activadee** [activadee/videocraft#18]
## Risk Level: HIGH
**Impact:** Service abuse, resource exhaustion, unfair usage

## Description
Current rate limiting is insufficient and doesn't cover all endpoints or provide user-specific limitations.

## Affected Files
- `internal/api/middleware/ratelimit.go:42-45`

## Components Breakdown
- [ ] Per-user rate limiting
- [ ] Rate limiting on all endpoints
- [ ] Distributed rate limiting support
- [ ] Different limits for different endpoint types
- [ ] Rate limit monitoring and alerting

## Specific Actions Needed
1. Implement per-user rate limiting
2. Apply rate limiting to all API endpoints
3. Add distributed rate limiting capability
4. Configure different limits per endpoint type
5. Add monitoring and alerting

## Acceptance Criteria
- [ ] All endpoints have appropriate rate limits
- [ ] Per-user limits are enforced
- [ ] Distributed rate limiting works in cluster deployments
- [ ] Rate limit exceeded responses are proper
- [ ] Monitoring shows rate limiting effectiveness
- [ ] Performance impact is minimal

## Timeline
**Day 25**

## Owner
Backend Team

**Comment by activadee** [comment]
## 🏗️ Implementation Strategy: Enhanced Rate Limiting Architecture

Based on our Multi-LLM validated plan, here are the detailed implementation specifications:

### 📐 System Architecture

```
┌─────────────────┐    ┌─────────────────┐    ┌─────────────────┐
│   HTTP Request  │───▶│  Auth Middleware │───▶│ Rate Limit MW   │
└─────────────────┘    └─────────────────┘    └─────────────────┘
                                                        │
                                                        ▼
┌─────────────────────────────────────────────────────────────────┐
│                  Enhanced Rate Limiter                          │
│  ┌─────────────────┐              ┌─────────────────────────┐   │
│  │  L1 Local Cache │◀────────────▶│    Policy Engine        │   │
│  │  (Read-Only)    │              │  (YAML Configuration)   │   │
│  │  - Policies     │              │  - Endpoint Limits      │   │
│  │  - Limits       │              │  - User Tiers          │   │
│  │  - TTL: 60s     │              │  - Hot Reload          │   │
│  └─────────────────┘              └─────────────────────────┘   │
│           │                                    │                │
│           ▼                                    ▼                │
│  ┌─────────────────┐              ┌─────────────────────────┐   │
│  │ Rate Limit Check│              │   Circuit Breaker       │   │
│  │ Logic           │              │   - Redis Health        │   │
│  └─────────────────┘              │   - Fallback Mode       │   │
│           │                       └─────────────────────────┘   │
│           ▼                                                     │
│  ┌─────────────────────────────────────────────────────────┐   │
│  │              L2 Redis Cluster                          │   │
│  │  ┌─────────────┐  ┌─────────────┐  ┌─────────────┐     │   │
│  │  │   Master    │  │   Slave 1   │  │   Slave 2   │     │   │
│  │  │ Lua Scripts │  │ Read Replica│  │ Read Replica│     │   │
│  │  │ Counters    │  │             │  │             │     │   │
│  │  └─────────────┘  └─────────────┘  └─────────────┘     │   │
│  └─────────────────────────────────────────────────────────┘   │
└─────────────────────────────────────────────────────────────────┘
                                │
                                ▼
┌─────────────────────────────────────────────────────────────────┐
│                    Monitoring Stack                             │
│  ┌─────────────┐    ┌─────────────┐    ┌─────────────────┐     │
│  │ Prometheus  │───▶│   Grafana   │───▶│   AlertManager  │     │
│  │ Metrics     │    │ Dashboards  │    │   Notifications │     │
│  └─────────────┘    └─────────────┘    └─────────────────┘     │
└─────────────────────────────────────────────────────────────────┘
```

### 🔧 Core Components

#### 1. Enhanced Rate Limiting Middleware
- **Location**: `internal/api/middleware/ratelimit.go`
- **Purpose**: Main request interception and rate limit enforcement
- **Features**: User context extraction, L1/L2 cache routing, circuit breaker integration

#### 2. L1 Read-Only Cache
- **Location**: `internal/infrastructure/cache/local.go`  
- **Purpose**: Ultra-fast (<1ms) policy lookups
- **Technology**: Ristretto cache with TTL-based invalidation
- **Scope**: Rate limit policies and configurations only

#### 3. L2 Redis Cluster
- **Location**: `internal/infrastructure/redis/ratelimiter.go`
- **Purpose**: Distributed rate limit counter enforcement
- **Technology**: Redis cluster with Lua scripts for atomic operations
- **Algorithms**: Sliding window (critical endpoints), Token bucket (others)

#### 4. Circuit Breaker
- **Location**: `internal/api/middleware/circuitbreaker.go`
- **Purpose**: Graceful degradation when Redis unavailable
- **Features**: Auto-recovery, configurable thresholds, local fallback

#### 5. Policy Engine
- **Location**: `config/ratelimit.yaml`
- **Purpose**: Dynamic configuration management
- **Features**: User tiers, endpoint-specific limits, hot reload

### 🎯 Request Flow Implementation

```go
// Detailed request processing flow:
func (erl *EnhancedRateLimiter) Middleware() gin.HandlerFunc {
    return func(c *gin.Context) {
        // 1. Extract user context from auth middleware
        userID := extractUserID(c)
        endpoint := c.Request.URL.Path
        
        // 2. Get rate limit policy from L1 cache (<1ms)
        policy, err := erl.l1Cache.GetPolicy(userID, endpoint)
        
        // 3. Check circuit breaker status
        if erl.breaker.IsOpen() {
            // Fallback to local rate limiting
            allowed := erl.localFallback(userID, endpoint, policy)
        } else {
            // 4. Check rate limit via L2 Redis
            allowed, err := erl.l2Store.CheckRateLimit(userID, endpoint, policy)
        }
        
        // 5. Handle rate limit exceeded
        if \!allowed {
            erl.handleRateLimit(c, policy) // HTTP 429 with retry headers
            return
        }
        
        // 6. Record metrics and continue
        erl.metrics.RecordRequest(userID, endpoint, "allowed")
        c.Next()
    }
}
```

### 📊 Configuration Structure

```yaml
# config/ratelimit.yaml
rate_limiting:
  enabled: true
  default_window: "1m"
  
  # User tiers with different limits
  user_tiers:
    free:
      global_limit: 100      # requests per minute
      burst_allowance: 10
      endpoint_limits:
        "/api/v1/videos": 10
        "/api/v1/jobs": 20
        "/health": 1000
    
    premium:
      global_limit: 1000
      burst_allowance: 50
      endpoint_limits:
        "/api/v1/videos": 100
        "/api/v1/jobs": 200
    
    enterprise:
      global_limit: 10000
      burst_allowance: 200
      endpoint_limits:
        "/api/v1/videos": 1000
        "/api/v1/jobs": 2000

  # Critical endpoints using sliding window
  critical_endpoints:
    - "/api/v1/videos"
    - "/api/v1/jobs/*/cancel"
  
  # Redis cluster configuration
  redis:
    cluster_mode: true
    addresses:
      - "redis-node-1:6379"
      - "redis-node-2:6379" 
      - "redis-node-3:6379"
    pool_size: 10
    dial_timeout: "5s"
  
  # Circuit breaker settings
  circuit_breaker:
    max_failures: 5
    timeout: "30s"
```

### 🔄 Key Algorithms

#### Sliding Window (Critical Endpoints)
```lua
-- Lua script for atomic sliding window operations
local key = KEYS[1]
local window = tonumber(ARGV[1])  -- window size in seconds
local limit = tonumber(ARGV[2])   -- max requests in window
local now = tonumber(ARGV[3])     -- current timestamp

-- Remove expired entries
redis.call('ZREMRANGEBYSCORE', key, 0, now - window)

-- Count current requests in window
local current = redis.call('ZCARD', key)

if current < limit then
    redis.call('ZADD', key, now, now .. ':' .. math.random())
    redis.call('EXPIRE', key, window)
    return {1, limit - current - 1}  -- [allowed, remaining]
else
    return {0, 0}  -- [denied, remaining]
end
```

#### Token Bucket (Standard Endpoints)
- Refill rate based on user tier
- Burst capacity for temporary spikes
- Efficient for non-critical endpoints

### ⚡ Performance Optimizations

1. **L1 Cache**: <1ms policy lookups via Ristretto
2. **Redis Pipelining**: Batch multiple rate limit checks  
3. **Lua Scripts**: Atomic operations prevent race conditions
4. **Connection Pooling**: Persistent Redis connections
5. **Smart Routing**: Critical vs non-critical endpoint handling

### 🔒 Security Features

1. **Multi-tier Validation**: L1 policy + L2 enforcement
2. **Tamper-proof Counters**: Redis atomic operations
3. **IP + User Limiting**: Defense against distributed attacks
4. **Audit Logging**: Complete rate limiting event trail
5. **Circuit Breaker**: Prevents cascade failures

### 📈 Monitoring Integration

```go
// Prometheus metrics collection
type PrometheusMetrics struct {
    requestsTotal    *prometheus.CounterVec    // Total requests by endpoint/user
    requestDuration  *prometheus.HistogramVec  // Request processing latency
    rateLimitHits    *prometheus.CounterVec    // Rate limit allow/deny counts
    cacheHitRatio    *prometheus.GaugeVec     // L1 cache effectiveness
    redisConnections *prometheus.GaugeVec     // Redis cluster health
    circuitBreaker   *prometheus.GaugeVec     // Circuit breaker state
}
```

### 🎯 Response Format

```json
// Rate limit exceeded response (HTTP 429)
{
    "error": "Rate limit exceeded",
    "code": "RATE_LIMIT_EXCEEDED",
    "details": {
        "limit": 100,
        "window": "1m",
        "reset_at": 1642678800,
        "retry_after": 45
    }
}
```

### 📋 Implementation Schedule

**Week 1**: Domain models, interfaces, failing tests (RED phase)
**Week 2-3**: Core implementation with Redis integration (GREEN phase)  
**Week 4**: Performance optimization, monitoring, documentation (REFACTOR phase)

**Next Step**: Begin TDD RED phase implementation 🚀
